### ISSUE TITLE
Typo in TripAdvisor Experience

### ISSUE THREAD

**Issue by Chris-Perkins** [luispadron/ConversationalPortfolio#1]
**Expected Behavior**  
- Expected "continuous" to be spelled correctly when viewing TripAdvisor experience

**Current Behavior**  
- Currently says "I also learned industry best practices like code reviews and continuos integration!"

**Possible Solution**  
- Fix typo in trip advisor json

**Steps to Reproduce**  
1. Enter your name
1. Click "work experience"
1. Select "TripAdvisor"
1. Observe results

**Context (Environment)**  
- Prod

Detailed Description  
- I don't want to write one

Possible Implementation
- In `./assets/json/opt-tripadvisor.json`, change all occurrences of "continuos" to "continuous".

**Comment by Chris-Perkins** [comment]
Here's an image of the issue.

![image](https://user-images.githubusercontent.com/15268274/45069500-daf8f100-b09a-11e8-93f3-524347bcc5c0.png)

**Comment by luispadron** [comment]
You’re the best
